[build]
  command = "npm run build"
  publish = "build/client"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["@react-router/node", "@react-router/serve"]

[[headers]]
  for = "/build/client/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Serve static assets directly
[[redirects]]
  from = "/build/client/*"
  to = "/build/client/:splat"
  status = 200

# Handle all other routes through the React Router function
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
  force = true 