[build]
  command = "npm run build"
  publish = "build/client"
  functions = "build/server"

[functions]
  node_bundler = "esbuild"

[[headers]]
  for = "/build/client/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200 