[build]
  command = "npm run build"
  publish = "build/client"
  functions = "build/server"

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@react-router/node", "@react-router/serve"]

[[headers]]
  for = "/build/client/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Handle all routes through the server function
[[redirects]]
  from = "/build/client/*"
  to = "/build/client/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/index"
  status = 200
  force = true 